### ISSUE TITLE
Connect fails instead of simply returning null

### ISSUE THREAD

**Issue by arushirai1** [p3sn/magento-soap-promise#1]
I propose there be a line which checks whether the connection (like the auth keys) are valid before proceeding. It would prevent the following error:
`
TypeError: Cannot read property 'login' of undefined
    at /home/arai4/Downloads/test_stuff/node_modules/magento-soap-promise/magento-soap-promise.js:29:20
    at /home/arai4/Downloads/test_stuff/node_modules/strong-soap/src/soap.js:49:5
    at /home/arai4/Downloads/test_stuff/node_modules/strong-soap/src/soap.js:31:16
    at /home/arai4/Downloads/test_stuff/node_modules/strong-soap/src/parser/wsdl.js:437:13
    at Request._callback (/home/arai4/Downloads/test_stuff/node_modules/strong-soap/src/http.js:136:9)
    at Request.self.callback (/home/arai4/Downloads/test_stuff/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/arai4/Downloads/test_stuff/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
`

**Comment by p3sn** [comment]
ok, good idea. tnx for your feedback
